"""Generate a Markdown research brief from the latest collected data.

Run from the terminal:   python -m fire.brief

Writes briefs/brief_YYYY-MM-DD.md. Run the collector first so there is
fresh data to summarise.
"""
from __future__ import annotations

from datetime import date

from . import db
from .config import BRIEFS_DIR, ticker_layers
from .valuation import score_valuation


def _fmt(value, spec="{:.2f}", dash="—"):
    if value is None:
        return dash
    try:
        return spec.format(value)
    except Exception:
        return dash


def build_brief() -> str:
    """Build the brief text. Returns Markdown."""
    layers = ticker_layers()
    today = date.today().isoformat()
    lines = [f"# FIRE Research Brief — {today}", ""]

    with db.connect() as conn:
        snaps = db.latest_snapshots(conn)
        last_run = db.get_meta(conn, "last_run", "never")

        if not snaps:
            return ("# FIRE Research Brief\n\n"
                    "No data collected yet. Run `python -m fire.collector` first.\n")

        # Score every name in the watchlist.
        scored = []
        for s in snaps:
            sd = dict(s)
            ps_hist = [r["price_to_sales"]
                       for r in db.snapshot_history(conn, sd["ticker"])]
            scored.append((sd, score_valuation(sd, ps_hist)))

        lines.append(f"_Data last collected: {last_run}. "
                     f"Watchlist: {len(snaps)} stocks._")
        lines.append("")

        # --- Valuation signals ---------------------------------------------
        attractive = [x for x in scored if x[1]["label"] == "Attractive"]
        rich = [x for x in scored if x[1]["label"] == "Rich"]

        lines.append("## Valuation signals")
        lines.append("")
        if attractive:
            lines.append("**Screening as attractive** — worth a closer look; "
                         "a long-term entry or a cash-secured put could be "
                         "modelled here. Not a buy call.")
            lines.append("")
            for sd, val in attractive:
                lines.append(f"- **{sd['ticker']}** ({layers.get(sd['ticker'], '')}) "
                             f"— {'; '.join(val['notes'])}")
            lines.append("")
        if rich:
            lines.append("**Screening as rich** — if you hold these, a covered "
                         "call may be worth modelling. Not a sell call.")
            lines.append("")
            for sd, val in rich:
                lines.append(f"- **{sd['ticker']}** ({layers.get(sd['ticker'], '')}) "
                             f"— {'; '.join(val['notes'])}")
            lines.append("")
        if not attractive and not rich:
            lines.append("_Nothing screening as notably cheap or rich today._")
            lines.append("")

        # --- Upcoming earnings ---------------------------------------------
        lines.append("## Earnings in the next 14 days")
        lines.append("")
        upcoming = db.upcoming_earnings(conn, days=14)
        if upcoming:
            for e in upcoming:
                lines.append(f"- **{e['ticker']}** — {e['earnings_date']} "
                             f"(estimate EPS {_fmt(e['eps_estimate'])})")
        else:
            lines.append("_None scheduled._")
        lines.append("")

        # --- Recent surprises ----------------------------------------------
        lines.append("## Recent earnings surprises (last 30 days)")
        lines.append("")
        surprises = db.recent_surprises(conn, days=30)
        if surprises:
            for e in surprises:
                sp = e["surprise_pct"]
                tag = "beat" if (sp or 0) >= 0 else "miss"
                lines.append(f"- **{e['ticker']}** — {e['earnings_date']}: "
                             f"actual {_fmt(e['eps_actual'])} vs "
                             f"estimate {_fmt(e['eps_estimate'])} "
                             f"({tag} {_fmt(sp, '{:+.1f}')}%)")
        else:
            lines.append("_No reported results in the window._")
        lines.append("")

        # --- Recent filings ------------------------------------------------
        lines.append("## SEC filings in the last 7 days")
        lines.append("")
        filings = db.recent_filings(conn, days=7)
        if filings:
            for f in filings:
                lines.append(f"- **{f['ticker']}** {f['form']} "
                             f"({f['filing_date']}) — [{f['title']}]({f['url']})")
        else:
            lines.append("_No new filings._")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by FIRE. Informational only — not investment "
                 "advice. Valuation labels are screening starting points, "
                 "not buy/sell calls._")
    return "\n".join(lines)


def main():
    BRIEFS_DIR.mkdir(parents=True, exist_ok=True)
    text = build_brief()
    out = BRIEFS_DIR / f"brief_{date.today().isoformat()}.md"
    out.write_text(text)
    print(f"Brief written to {out}")


if __name__ == "__main__":
    main()
